Tc03
viethuynh140499/railway pull request #13
Opened 2021-05-04 08:10 UTC by viethuynh140499

2021-05-05 10:01 UTC, fey031 commented on src/test/java/test_cases/LoginTests.java
> +    Assert.assertEquals(actualResult, expectedResult);
Add assert message.
Assert.assertEquals(actualResult, expectedResult, message);

2021-05-05 10:02 UTC, fey031 commented on src/test/java/test_cases/LoginTests.java
> +    Assert.assertEquals(actualResult, expectedResult);
same above

2021-05-05 10:02 UTC, fey031 commented on src/test/java/test_cases/LoginTests.java
> +    Assert.assertEquals(actualResult, expectedResult);
same above

2021-05-05 10:22 UTC, viethuynh140499 commented on src/test/java/test_cases/LoginTests.java
> +    Assert.assertEquals(actualResult, expectedResult);
Yes, I added assert message

2021-05-05 10:22 UTC, viethuynh140499 commented on src/test/java/test_cases/LoginTests.java
> +    Assert.assertEquals(actualResult, expectedResult);
Yes, I added assert message

2021-05-05 10:22 UTC, viethuynh140499 commented on src/test/java/test_cases/LoginTests.java
> +    Assert.assertEquals(actualResult, expectedResult);
Yes, I added assert message

2021-05-06 02:52 UTC, tanmle requested changes

2021-05-06 02:52 UTC, tanmle commented on src/test/resources/testNG.xml
>  </suite>
break line.

2021-05-06 02:52 UTC, tanmle commented on src/test/java/test_cases/LoginTests.java
> +
redundant line

2021-05-06 03:54 UTC, viethuynh140499 commented on src/test/resources/testNG.xml
>  </suite>
yes, I added break line

2021-05-06 03:55 UTC, viethuynh140499 commented on src/test/java/test_cases/LoginTests.java
> +
yes, I remove redundant line

2021-05-06 04:00 UTC, fey031 commented on src/test/java/test_cases/LoginTests.java
> +    User user = new User(Constant.USERNAME, DataHelper.getRandomInvalidPassword());
We don't need to use random password here, you can use any string for it

2021-05-06 04:01 UTC, fey031 approved these changes
LGTM

2021-05-06 08:16 UTC, merged